### ISSUE TITLE
Error: Call to device timed out - Got SIGTERM, shutting down Homebridge..

### ISSUE THREAD

**Issue by DJay-X** [ch3rn1k/homebridge-multipurpose-kettle#10]
Hi there. I hope you are well.

I recently get a lot of Homebridge shutting down, because of the plugin is having a time out?
The kettle was/is connected to power all the time and Wifi was not having a noticeable issue during the past time.

However, the plugin probably should not force the entire homebridge shutting down. 

May you'll find the time to invest or a solution with an upcoming update in the future.

As always thanks again. 🙏

```
[2020-10-23 18:02:48] 
Error: Call to device timed out
    at retry (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:500:8
 {
  code: 'timeout'
}
Error: Call to device timed out
    at retry (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:500:8
 {
  code: 'timeout'
}
[2020-10-23 18:17:27] Got SIGTERM, shutting down Homebridge...
[2020-10-23 18:17:29] [Wasserkocher] getWorkStatus Error: Call to device timed out
    at retry (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:500:8
 {
  code: 'timeout'
}
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:310:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:310:25
```

**Comment by ch3rn1k** [comment]
Hey ya, sorry for missing, no time. About that error - I can't reproduce that one. Is it still exist? Thanks.
