### ISSUE TITLE
No kettle was found... Failed to discover the device. Next try in 2 min! Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by DJay-X** [ch3rn1k/homebridge-multipurpose-kettle#8]
Who else? Me again. ;) 

I noticed every time Homebridge has been restarted, this error occurs.
First no kettle found.
And even opening Home / Eve App it is marked as not reachable.
Only after a the 2 minutes the update in the log is showing, that the kettle now was discovered.
See log and time stamps.

Just to point to this, without the need of an immediate action. :)

Thanks Alex.

```
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:38:16] [Wasserkocher] Failed to discover the device. Next try in 2 min! Error: Could not connect to device, handshake timeout
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:427:17)
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]:     at listOnTimeout (internal/timers.js:549:17)
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]:     at processTimers (internal/timers.js:492:7) {
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]:   code: 'timeout',
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]:   device: null
Jul 18 15:38:16 raspberrypi-3BPlus homebridge[10320]: }
Jul 18 15:38:27 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:38:27] [Wasserkocher] No kettle was found...
Jul 18 15:38:27 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:38:27] [Wasserkocher] No kettle was found...
Jul 18 15:39:26 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:39:26] [Wasserkocher] No kettle was found...
Jul 18 15:39:37 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:39:37] [Wasserkocher] No kettle was found...
Jul 18 15:40:17 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:40:17] [Wasserkocher] Successfully created custom mode with 90°C!
Jul 18 15:40:17 raspberrypi-3BPlus homebridge[10320]: [2020-7-18 15:40:17] [Wasserkocher] Successfully set sound to "TRUE" state!
```

**Comment by ch3rn1k** [comment]
Hello! This one error only fires if Homebridge can't connect to Kettle, I can't help with that...

**Comment by DJay-X** [comment]
All good. Thanks. Just wondering because every time starting homebridge this is showing up in the log at start. And of course the kettle is online and reachable. What the log confirms after 2 minutes. No worries. :)
