### ISSUE TITLE
TypeError: miioDelayPromise is not a function

### ISSUE THREAD

**Issue by DJay-X** [ch3rn1k/homebridge-multipurpose-kettle#9]
Aaaand it's me gain. 😅

Today we had a power outage only in the kitchen. The power was back shortly but this seems to irritate the plugin.
Probably the same if you would just unplug the the kettle for cleaning the base or so?

However because of this the plugin let homebridge shutdown. Probably this shouldn't crash the whole homebridge.
Maybe something for a next update to tweak. Nothing critical though and just want to let you know.

Have nice week.

```
[2020-7-21 13:36:42] [Wasserkocher] getWorkStatus Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
[2020-7-21 13:36:42] Got SIGTERM, shutting down Homebridge...
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
```

**Comment by DJay-X** [comment]
Strange.. this morning the homebridge shutdown forced by the plugin did happen again. 
This time nothing to do with base without power. Just about of the blue when already running the boiler.

```
[2020-7-22 9:00:15] [Wasserkocher] Work in progress! [TEMP 68, HEAT 90]
[2020-7-22 9:00:25] [Wasserkocher] Work in progress! [TEMP 70, HEAT 90]
[2020-7-22 9:00:35] [Wasserkocher] Work in progress! [TEMP 72, HEAT 90]
[2020-7-22 9:00:45] [Wasserkocher] Work in progress! [TEMP 73, HEAT 90]
[2020-7-22 9:00:55] [Wasserkocher] Work in progress! [TEMP 75, HEAT 90]
[2020-7-22 9:01:05] [Wasserkocher] Work in progress! [TEMP 77, HEAT 90]
Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[2020-7-22 9:01:27] Got SIGTERM, shutting down Homebridge...
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
[2020-7-22 9:01:27] [Wasserkocher] getWorkStatus Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
```

**Comment by DJay-X** [comment]
After a couple of day, unfortunately the plugin crashed homebridge again. 🤷🏼‍♂️

```
[2020-7-29 18:20:47] [Wasserkocher] getWorkStatus Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:294:21
[2020-7-29 18:20:48] Got SIGTERM, shutting down Homebridge...
[2020-7-29 18:20:48] [AppleTvPlatform] Shutting down Apple TV clients...
[2020-7-29 18:20:48] [TedeePlatform] Shutting down timers...
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:319:25
```

**Comment by ch3rn1k** [comment]
Hello, sorry for delay. Please try `2.2.5`v

**Comment by DJay-X** [comment]
I updated and will see in the next days what happens.

And no need for a sorry from your side. It was no hurry. 
Thanks again Alex.

**Comment by ch3rn1k** [comment]
Hello! How it's going?

**Comment by DJay-X** [comment]
Morning.. :) Thanks for the reminder. I was out of home a couple of days.
But Homebridge didn't face any problem recently and the plugin is running. 
I did some restart of homebridge from outside and the only thing I noticed is that at reboot the kettle is not found every time.
After 3 Minutes the log is showing that the kettle was then discovered.
Stange because the kettle is of course all the time on the power and online. 
But no crash or shutdown of homebridge because of the plugin and no other error in the log.

Let's close this issue I think. 

Thanks again for your friendly help. As always I appreciate that you are interested to help and fix some smaller bugs.

**Comment by ch3rn1k** [comment]
Thanks for your feedback!

**Comment by DJay-X** [comment]
@ch3rn1k Not sure if it belongs here but I don't want to open a new ticket. 🙈

The Plugin crashed/shutdown Homebridge because of the kettle was not on powert (on purpose).
Only for a minute while cleaning the kitchen. However this was giving the plugin trouble and it shut down the entire Homebridge. I think a complete shutdown because of this is not good. 
What do you think? Maybe something for a next update. ;) 


```
Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[2020-8-25 9:57:13] Got SIGTERM, shutting down Homebridge...
[2020-8-25 9:57:15] [Wasserkocher] getWorkStatus Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-multipurpose-kettle/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:310:25
TypeError: miioDelayPromise is not a function
    at /usr/local/lib/node_modules/homebridge-multipurpose-kettle/index.js:310:25
```
